# Generated by Django 3.2.19 on 2023-05-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nnr_payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='consumption_records',
            new_name='consumption_record',
        ),
    ]
